spring.application.name=scooby-doo-livro
spring.datasource.url=jdbc:postgresql://ep-blue-pine-ahfqax3b-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_6fNLkvpcmS5D&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6fNLkvpcmS5D
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_batch_fetch_size=50
api.security.token.secret=${JWT_SECRET:i-miss-fortnite2018}